### ISSUE TITLE
Add logger logging literally everywhere

### ISSUE THREAD

**Issue by OndrejValenta** [KeenMate/fluently-sharepoint#8]
Add logging method calls to extension methods.

The logic should be like this

- Operations modifying data/structure or execution of context as Info level types of log entries
- Operations simply fetching data or having second level purpose like setting up timeouts or FailHandlers as Debug level of log entries
- Everything else including performance log entries as Trace types of log entries

**Comment by albertmoravec** [comment]
Resolved by 63f57818eadeb25c8cb438a4777250bf28c6b1a6
